Ext.define('Ssp.model.tool.studentintake.StudentDemographics', {
    extend: 'Ssp.model.AbstractBaseTO',
    fields: ['id',
             'abilityToBenefit',
             'anticipatedStartTerm',
             'anticipatedStartYear',
    		 'isLocal',
		     'countryOfResidence',
	         'paymentStatus',
	         'maritalStatus',
   			 'ethnicity',
   			 'gender',
   			 'citizenship',
   			 'veteranStatus',
   			 'countryOfCitizenship',
   			 'primaryCaregiver',
   			 'caregiverTypeChild',
   			 'numberOfChildren',
   			 'childAges',
   			 'childCareNeeded',
   			 'childCareArrangement',
   			 'employed',
   			 'placeOfEmployment',
   			 'wage',
   			 'shift',
   			 'totalHoursWorkedPerWeek']
    
});