Ext.define('Ssp.model.StudentTO', {
    extend: 'Ext.data.Model',
    fields: ['id',
    		 'studentIntakeCreatedDate',
    		 'photoUrl',
    		 'uniqueSchoolUserId',
    		 'name',
    		 'firstName',
    		 'middleInitial',
    		 'lastName',
    		 'homePhone',
    		 'cellPhone',
    		 'workPhone',
    		 'address',
    		 'city',
    		 'state',
    		 'zipCode',
    		 'emailPrimary',
    		 'emailSecondary',
    		 'dateOfBirth',
    		 'studentType',
    		 'programStatus',
    		 'registrationStatus',
    		 'paymentStatus',
    		 'cumGPA',
    		 'academicPrograms',
    		 'tools']
    
});