Ext.define('Ssp.model.StudentTO', {
    extend: 'Ssp.model.AbstractBaseTO',
    fields: ['id',
    		 'studentIntakeCreatedDate',
    		 'photoUrl',
    		 'schoolId',
    		 'name',
    		 'firstName',
    		 'middleInitial',
    		 'lastName',
    		 'homePhone',
    		 'cellPhone',
    		 'workPhone',
    		 'address',
    		 'city',
    		 'state',
    		 'zipCode',
    		 'primaryEmailAddress',
    		 'secondaryEmailAddress',
    		 'birthDate',
    		 'studentType',
    		 'programStatus',
    		 'registrationStatus',
    		 'paymentStatus',
    		 'cumGPA',
    		 'academicPrograms',
    		 'tools']
    
});