/*
 * Licensed to Apereo under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Apereo licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License.  You may obtain a
 * copy of the License at the following location:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
// Generated by CoffeeScript 1.4.0
(function() {
  var $, context, selfHelpGuideId, viewModel;

  $ = jQuery;

  context = window.context || (window.context = {});

  context.sessionService || (context.sessionService = new mygps.service.SessionService("../api/1/session"));

  context.taskService || (context.taskService = new mygps.service.TaskService("../api/1/mygps/task"));

  context.selfHelpGuideService || (context.selfHelpGuideService = new mygps.service.SelfHelpGuideService("../api/1/mygps/selfhelpguide"));

  context.selfHelpGuideResponseService || (context.selfHelpGuideResponseService = new mygps.service.SelfHelpGuideResponseService("../api/1/mygps/selfhelpguideresponse"));

  context.challengeReferralService || (context.challengeReferralService = new mygps.service.ChallengeReferralService("../api/1/mygps/challengereferral"));

  context.session || (context.session = new mygps.session.Session(context.sessionService));

  selfHelpGuideId = $.parameter("selfHelpGuideId");

  viewModel = new mygps.viewmodel.SelfHelpGuideViewModel(context.session, context.taskService, context.selfHelpGuideService, context.selfHelpGuideResponseService, context.challengeReferralService);

  viewModel.load(selfHelpGuideId);

  window.viewModel = viewModel;

  $('#guide-introduction-page').live('pagecreate', function() {
    var guideIntroductionPage;
    guideIntroductionPage = this;
    $("body").loadTemplates({
      bannerTemplate: "/ssp/MyGPS/templates/banner.html",
      footerTemplate: "/ssp/MyGPS/templates/footer.html"
    }).done(function() {
      ko.applyBindings(viewModel, guideIntroductionPage);
    });
  });

  $('#guide-question-page').live('pagecreate', function() {
    var guideQuestionPage;
    guideQuestionPage = this;
    $("body").loadTemplates({
      bannerTemplate: "/ssp/MyGPS/templates/banner.html",
      footerTemplate: "/ssp/MyGPS/templates/footer.html",
      questionTemplate: "/ssp/MyGPS/templates/question.html"
    }).done(function() {
      ko.applyBindings(viewModel, guideQuestionPage);
    });
  });

  $('#guide-referrals-page').live('pagecreate', function() {
    var guideReferralsPage;
    guideReferralsPage = this;
    $("body").loadTemplates({
      bannerTemplate: "/ssp/MyGPS/templates/banner.html",
      footerTemplate: "/ssp/MyGPS/templates/footer.html",
      tasksTemplate: "/ssp/MyGPS/templates/tasks.html",
      taskTemplate: "/ssp/MyGPS/templates/task.html",
      taskDetailTemplate: "/ssp/MyGPS/templates/taskdetail.html",
      challengeTemplate: "/ssp/MyGPS/templates/challenge.html",
      referralTemplate: "/ssp/MyGPS/templates/referral.html"
    }).done(function() {
      ko.applyBindings(viewModel, guideReferralsPage);
    });
  });

  $('#guide-summary-page').live('pagecreate', function() {
    var guideSummaryPage;
    guideSummaryPage = this;
    $("body").loadTemplates({
      bannerTemplate: "/ssp/MyGPS/templates/banner.html",
      footerTemplate: "/ssp/MyGPS/templates/footer.html"
    }).done(function() {
      ko.applyBindings(viewModel, guideSummaryPage);
    });
  });

}).call(this);
