// Generated by CoffeeScript 1.3.1
(function() {

  (function($) {
    var context;
    context = window.context || (window.context = {});
    context.sessionService || (context.sessionService = new mygps.service.SessionService("../api/session"));
    context.taskService || (context.taskService = new mygps.service.TaskService("../api/mygps/task"));
    context.challengeService || (context.challengeService = new mygps.service.ChallengeService("../api/mygps/challenge"));
    context.challengeReferralService || (context.challengeReferralService = new mygps.service.ChallengeReferralService("../api/mygps/challengereferral"));
    context.session || (context.session = new mygps.session.Session(context.sessionService));
    return $('#search-page').live('pagecreate', function() {
      var searchPage, viewModel;
      searchPage = this;
      viewModel = new mygps.viewmodel.ChallengeReferralSearchViewModel(context.session, context.taskService, context.challengeService, context.challengeReferralService);
      window.viewModel = viewModel;
      $("body").loadTemplates({
        bannerTemplate: "/ssp/MyGPS/templates/banner.html",
        footerTemplate: "/ssp/MyGPS/templates/footer.html",
        tasksTemplate: "/ssp/MyGPS/templates/tasks.html",
        taskTemplate: "/ssp/MyGPS/templates/task.html",
        taskDetailTemplate: "/ssp/MyGPS/templates/taskdetail.html",
        customTaskTemplate: "/ssp/MyGPS/templates/customtask.html",
        challengeTemplate: "/ssp/MyGPS/templates/challenge.html",
        referralTemplate: "/ssp/MyGPS/templates/referral.html"
      }).done(function() {
        ko.applyBindings(viewModel, searchPage);
      });
      $('#search-page').live('pagebeforeshow', function() {
        window.viewModel = viewModel;
        viewModel.load();
      });
    });
  })(jQuery);

}).call(this);
