// Generated by CoffeeScript 1.2.1-pre
(function() {
  var context;

  context = window.context || (window.context = {});

  $('#home-page').live('pagecreate', function(event) {
    var homePage, viewModel;
    homePage = this;
    viewModel = new ssp.controller.ApplicationViewController();
    window.viewModel = viewModel;
    $("body").loadTemplates({
      headerTemplate: "partials/header.html",
      navTemplate: "partials/top-nav.html",
      profileTemplate: "partials/profile.html",
      toolsNavTemplate: "partials/tools-nav.html",
      intakeTemplate: "partials/tools/student-intake.html",
      journalTemplate: "partials/tools/journal.html",
      studentTemplate: "partials/student.html",
      footerTemplate: "partials/footer.html"
    }).done(function() {
      ko.applyBindings(viewModel, homePage);
    });
    $('#home-page').live('pagebeforeshow', function() {
      window.viewModel = viewModel;
    });
  });

}).call(this);
