// Generated by CoffeeScript 1.2.1-pre
(function() {
  var AbstractService, AppController, ApplicationViewController, Challenges, Demographics, EducationLevels, EducationalGoal, EducationalPlan, FundingSources, MainViewController, Student, StudentService,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  namespace('ssp.controller', {
    AppController: AppController = (function() {

      AppController.name = 'AppController';

      function AppController() {
        this.studentService = new ssp.service.StudentService("/ssp/web/example");
        this.student || (this.student = new ssp.model.Student);
      }

      AppController.prototype.loadStudent = function(studentId) {
        var _this = this;
        this.studentService.getStudent(studentId, {
          result: function(result) {
            return _this.student = result;
          },
          fault: function(fault) {
            return alert(fault.responseText);
          }
        });
      };

      return AppController;

    })()
  });

  namespace('ssp.controller', {
    ApplicationViewController: ApplicationViewController = (function() {

      ApplicationViewController.name = 'ApplicationViewController';

      function ApplicationViewController() {
        this.currentPage = "partials/student.html";
        this.currentTool = "";
        this.currentSubNav = "partials/tools-nav.html";
        this.currentProfile = "partials/profile.html";
      }

      ApplicationViewController.prototype.displayTool = function(toolName) {
        return this.currentTool = "partials/tools/" + toolName + ".html";
      };

      return ApplicationViewController;

    })()
  });

  namespace('ssp.controller', {
    MainViewController: MainViewController = (function() {

      MainViewController.name = 'MainViewController';

      function MainViewController($route, $location) {
        this.route = $route;
        this.location = $location;
        this.route.when('/student', {
          template: 'ssp/partials/student.html',
          controller: ssp.controller.AppController
        });
      }

      return MainViewController;

    })()
  }, MainViewController.$inject = ['$route', '$location']);

  namespace('ssp.service', {
    AbstractService: AbstractService = (function() {

      AbstractService.name = 'AbstractService';

      function AbstractService(baseURL) {
        this.baseURL = baseURL;
      }

      AbstractService.prototype.createURL = function(value) {
        var _ref;
        return "" + ((_ref = this.baseURL) != null ? _ref : '') + value;
      };

      return AbstractService;

    })()
  });

  namespace('ssp.service', {
    StudentService: StudentService = (function(_super) {

      __extends(StudentService, _super);

      StudentService.name = 'StudentService';

      function StudentService(baseURL) {
        StudentService.__super__.constructor.call(this, baseURL);
      }

      StudentService.prototype.getStudent = function(studentId, callbacks) {
        return $.ajax({
          url: this.createURL("/get"),
          dataType: "json",
          success: function(result) {
            var student;
            student = ssp.model.Student.createFromTransferObject(result);
            return callbacks != null ? typeof callbacks.result === "function" ? callbacks.result(student) : void 0 : void 0;
          },
          error: function(fault) {
            return callbacks != null ? typeof callbacks.fault === "function" ? callbacks.fault(fault) : void 0 : void 0;
          }
        });
      };

      return StudentService;

    })(ssp.service.AbstractService)
  });

  namespace('ssp.model', {
    Student: Student = (function() {

      Student.name = 'Student';

      function Student(studentId, firstName, middleInitial, lastName, uniqueSchoolUserID, birthDate, emailSchool, emailHome, homePhone, workPhone, cellPhone, address, city, state, zipCode) {
        this.profilePicUrl = '/ssp/images/student-pic-small.png';
        this.studentId = studentId;
        this.firstName = firstName;
        this.middleInitial = middleInitial;
        this.lastName = lastName;
        this.uniqueSchoolUserID = uniqueSchoolUserID;
        this.birthDate = birthDate;
        this.emailSchool = emailSchool;
        this.emailHome = emailHome;
        this.homePhone = homePhone;
        this.workPhone = workPhone;
        this.cellPhone = cellPhone;
        this.address = address;
        this.city = city;
        this.state = state;
        this.zipCode = zipCode;
        this.demographics || (this.demographics = new ssp.model.studentintake.Demographics);
        this.educationalPlan || (this.educationalPlan = new ssp.model.studentintake.EducationalPlan);
        this.educationLevels || (this.educationLevels = new ssp.model.studentintake.EducationLevels);
        this.educationalGoal || (this.educationalGoal = new ssp.model.studentintake.EducationalGoal);
        this.fundingSources || (this.fundingSources = new ssp.model.studentintake.FundingSources);
        this.challenges || (this.challenges = new ssp.model.studentintake.Challenges);
      }

      Student.createFromTransferObject = function(studentTO) {
        return new Student(studentTO.studentId, studentTO.firstName, studentTO.middleInitial, studentTO.lastName, studentTO.uniqueSchoolUserID, studentTO.birthDate, studentTO.emailSchool, studentTO.emailHome, studentTO.homePhone, studentTO.workPhone, studentTO.cellPhone, studentTO.address, studentTO.city, studentTO.state, studentTO.zipCode);
      };

      return Student;

    })()
  });

  namespace('ssp.model.studentintake', {
    Challenges: Challenges = (function() {

      Challenges.name = 'Challenges';

      function Challenges(items) {
        this.items = [] | items;
      }

      return Challenges;

    })()
  });

  namespace('ssp.model.studentintake', {
    Demographics: Demographics = (function() {

      Demographics.name = 'Demographics';

      function Demographics(maritalStatus) {
        this.maritalStatus = maritalStatus;
      }

      return Demographics;

    })()
  });

  namespace('ssp.model.studentintake', {
    EducationLevels: EducationLevels = (function() {

      EducationLevels.name = 'EducationLevels';

      function EducationLevels(items) {
        this.items = [] | items;
      }

      return EducationLevels;

    })()
  });

  namespace('ssp.model.studentintake', {
    EducationalGoal: EducationalGoal = (function() {

      EducationalGoal.name = 'EducationalGoal';

      function EducationalGoal(careerGoal) {
        this.careerGoal = careerGoal;
      }

      return EducationalGoal;

    })()
  });

  namespace('ssp.model.studentintake', {
    EducationalPlan: EducationalPlan = (function() {

      EducationalPlan.name = 'EducationalPlan';

      function EducationalPlan(studentStatus) {
        this.studentStatus = studentStatus;
      }

      return EducationalPlan;

    })()
  });

  namespace('ssp.model.studentintake', {
    FundingSources: FundingSources = (function() {

      FundingSources.name = 'FundingSources';

      function FundingSources(items) {
        this.items = [] | items;
      }

      return FundingSources;

    })()
  });

}).call(this);
